In [2]:
#importing the required packages for the assignment
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.colors
import seaborn as sns
import os
%matplotlib inline

In [3]:
import os#parameter Setting for the notebook(Use as and when required)
#pd.set_option('display.max_columns', 500)
#os.chdir(r"C:\Users\Rajat\Machine Learning\machine-learning-ex\machine-learning-ex\Datasets")
#cwd = os.getcwd()  # Get the current working directory (cwd)
#files = os.listdir(cwd)  # Get all the files in that directory
os.getcwd()

'C:\\Users\\Rajat\\Machine Learning\\machine-learning-ex\\machine-learning-ex\\SupervisedLearningAssignments'

In [ ]:
1. Create a 1D array of numbers from 0 to 9.

2. Create a 3×3 numpy array of all True’s

3. Given an array as input, print only odd numbers as output

4. Replace all odd numbers in arr with -2

5. How to reshape an array?

6. Convert a 1D array to a 2D array with 2 rows

7. Given an array  a  = [1,2,3,4,5,6,7,8,9] , create  new array b from a such that b includes all odd numbers and 4 multiples. 

8. Given array, check if there are any null values and print them out. 

9. How to replace all missing values with 0 in a numpy array?

10. How to find the count of each unique number in a NumPy array?

11. How to convert a numeric to a categorical (text) array?

12. Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7. Exclude the elements which are divisible by both. 

13. Write a program to reverse an array and print (Don’t use inbuilt reverse functions)

In [12]:
#1. Create a 1D array of numbers from 0 to 9.
a = np.arange(10)    #.reshape(2,5), used to change the  shape of the array
print(a)
print(a.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [16]:
#2. Create a 3×3 numpy array of all True’s
b = np.ones((3,3),dtype = bool)
print(type(b))
print(b)

<class 'numpy.ndarray'>
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [33]:
#3 Given an array as input, print only odd numbers as output
#Considerinf 1d arrays:
b = list(map(int,input('Enter space seperated elements of the array: ').split()))
c=[i for i in b if i%2!=0]
print(set(c))

Enter space seperated elements of the array: 1 3 5 9 12
{1, 3, 5, 9}


In [35]:
#4. Replace all odd numbers in arr with -2
b = list(map(int,input('Enter space seperated elements of the array: ').split()))
b=[-2 if i%2!=0 else i for i in b]
print(b)

Enter space seperated elements of the array: 1 8 15 
[-2, 8, -2]


In [41]:
#5. How to reshape an array?
b = list(map(int,input('Enter space seperated elements of the array: ').split()))
c,d = map(int,input('Enter the shape: ').split())
b = np.array(b).reshape(c,d)
print('Shape of array is',b.shape)
print(b)

Enter space seperated elements of the array: 1 5 9 7 5 3
Enter the shape: 2 3 
Shape of array is (2, 3)
[[1 5 9]
 [7 5 3]]


In [43]:
#6. Convert a 1D array to a 2D array with 2 rows
b = list(map(int,input('Enter space seperated elements of the array: ').split()))
a = np.reshape(b, (-1, 2))
print(a)

Enter space seperated elements of the array: 1 5 9 7 5 3
[[1 5]
 [9 7]
 [5 3]]


In [50]:
#7. Given an array  a  = [1,2,3,4,5,6,7,8,9] , create  new array b from a such that b includes all odd numbers and 4 multiples.
a  = [1,2,3,4,5,6,7,8,9]
b = [i for i in a if (i%4==0 or i%2!=0)]
print(b)

[1, 3, 4, 5, 7, 8, 9]


In [55]:
#8.Given array, check if there are any null values and print them out
a=[1,55,None]
None in a

True

In [63]:
b= ['A', '','C']
b= [i for i in b if not i]
print(b)

['']


In [61]:
#9. How to replace all missing values with 0 in a numpy array?
a=[1,55,None]
a=[0 if i==None else i for i in a]
print(a)

[1, 55, 0]


In [66]:
b= ['A', '','C']
b= [i if i else 0 for i in b]
print(b)

['A', 0, 'C']


In [72]:
#10. How to find the count of each unique number in a NumPy array?
b = list(map(int,input('Enter space seperated elements of the array: ').split()))
print('Unique Numbers in list: ',len(set(b)))
#dictionary comprehension to get count of unique elements in an array
freq = {} 
for items in b: 
    freq[items] = b.count(items) 
print(freq)
di = {i:b.count(i) for i in b}
print(di)

Enter space seperated elements of the array: 1 5 5
Unique Numbers in list:  2
{1: 1, 5: 2}
{1: 1, 5: 2}


In [73]:
#11. How to convert a numeric to a categorical (text) array?
A = [1, 2 ,3]
A = [str(i) for i in A]
print(A)

['1', '2', '3']


In [79]:
#12. Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7. Exclude the elements which are divisible by both.
b = [i for i in range(99,300) if (i%5==0) ^ (i%7==0)]  
print(b)

[100, 110, 112, 115, 119, 120, 125, 126, 130, 133, 135, 145, 147, 150, 154, 155, 160, 161, 165, 168, 170, 180, 182, 185, 189, 190, 195, 196, 200, 203, 205, 215, 217, 220, 224, 225, 230, 231, 235, 238, 240, 250, 252, 255, 259, 260, 265, 266, 270, 273, 275, 285, 287, 290, 294, 295]


In [83]:
#13. Write a program to reverse an array and print (Don’t use inbuilt reverse functions)
a = [11,668,15616,561,651561,165165,156156,999999,155]
a[::-1]

[155, 999999, 156156, 165165, 651561, 561, 15616, 668, 11]